### ISSUE TITLE
Add prize breakdown for each place in specific draw result request

### ISSUE THREAD

**Issue by FCardeira** [pedro-mealha/euromillions-api#184]
Hello! Thank you for maintaining this useful API. I have a feature request that would enhance the detail of the draw information.

Currently, the euromillions-api fetches basic draw data from [euro-millions.com](https://euro-millions.com/), including the draw results, but it does not return the prize breakdown for each winning category or "place" (e.g., 5+2, 5+1, 5+0, etc.). This information is often essential for users interested in the prize amounts for different combinations.

### **Feature Request:**

**Objective:**
Extend the GET /draws/{id} endpoint to include the prize amounts for each place in the draw.

**Expected Data:**
- Prize for each winning category (e.g., 5+2, 5+1, 5+0, etc.)
- Number of winners for each category
- Place name (such as "5+2", "5+1", "4+2", etc.)

### **Implementation Notes:**
It seems that the prize information is available on the draw details page on the source website. This data could be scraped along with the existing information. This additional data would be helpful for users needing comprehensive results for statistical purposes or to track winning trends.

### **Example of Expected JSON Structure:**
```json
{
  "date": "Tue, 02 Jan 2024 00:00:00 GMT",
  "draw_id": 12024,
  "has_winner": false,
  "id": 1905,
  "numbers": [
    "7",
    "15",
    "18",
    "46",
    "49"
  ],
  "prizes": [
    {
      "place": "5+2",
      "winners": 1,
      "prize": 30000000
    },
    {
      "place": "5+1",
      "winners": 3,
      "prize": 1200000
    },
    {
      "place": "5+0",
      "winners": 10,
      "prize": 50000
    },
],
  "stars": [
    "10",
    "12"
  ]
}
```

Thank you for considering this request! Please let me know if you need any further information or if there are specific areas where I could help.

**Comment by pedro-mealha** [comment]
Thank you @FCardeira for your request!
I appreciate your interest in keeping this API up-to-date with new features.

During the weekend I will find the time to open a PR with the implementation.
I would suggest one change to your proposal:

```
(...)
"prizes": [
    {
      "matched_numbers": 5,
      "matched_stars": 2,
      "winners": 1,
      "prize": 30000000
    },
    {
      "matched_numbers": 5,
      "matched_stars": 1,
      "winners": 3,
      "prize": 1200000
    },
    {
      "matched_numbers": 5,
      "matched_stars": 0,
      "winners": 10,
      "prize": 50000
    },
    (...),
(...)
```

wdyt?

**Comment by FCardeira** [comment]
Yes, it's definitely better 😄

**Comment by pedro-mealha** [comment]
Just deployed version [v2.5.0](https://github.com/pedro-mealha/euromillions-api/releases/tag/v2.5.0) to prod!
You should now be able to have access to the requested feature!

Check the api-docs for more info!
https://euromillios-api.readme.io/reference/get_v1-draws
https://euromillios-api.readme.io/reference/get_v1-draws-id
